"""Synthetic telemetry for the AEGIS cyber-range."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class TelemetryType(str, Enum):
    """Observable activity categories generated by Red actions."""

    DISCOVERY_ACTIVITY = "discovery_activity"
    LATERAL_MOVEMENT = "lateral_movement"
    EXPLOIT_ATTEMPT = "exploit_attempt"
    PRIVILEGE_ESCALATION = "privilege_escalation"


@dataclass(frozen=True)
class TelemetryEvent:
    """A synthetic event that may be exposed to Blue."""

    event_type: TelemetryType
    source: str
    target: str | None = None

def telemetry_for_red_action(
    action_type: str,
    source: str,
    target: str | None = None,
) -> TelemetryEvent | None:
    """Generate deterministic telemetry for a Red action."""

    event_types = {
        "discover": TelemetryType.DISCOVERY_ACTIVITY,
        "move": TelemetryType.LATERAL_MOVEMENT,
        "exploit": TelemetryType.EXPLOIT_ATTEMPT,
        "escalate": TelemetryType.PRIVILEGE_ESCALATION,
    }

    event_type = event_types.get(action_type)

    if event_type is None:
        return None

    return TelemetryEvent(
        event_type=event_type,
        source=source,
        target=target,
    )